sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /PC_filter/agile/filtered_3dPC
    max_range: 1.1
    point_subsample: 6
    padding_offset: 0.03
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
